# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 080177ab8f57eb259337f67dd34a26630e9ced0fe0596445a3e9dc3473ef509b4bf09e22e4b2749cf1aa0ebc55e8bc3bfbd5a9a3f54ab5c1b745e741f19b7358

test:
  secret_key_base: 760c8695016695f440ec286c59c49a0546a2c5bded427a1112f685c0a05a32578a81ede2e7d27f482d8ee364f4c80b26d9959c1ae6c332161d04babbf67b7cb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
